name: isupplytask1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Icon generator
  flutter_launcher_icons: ^0.14.4

  # Splash screen animation
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  flutter_native_splash: ^2.4.6
  animated_text_kit: ^4.2.3
  # 🔥 Firebase Core - Required for all Firebase services
  firebase_core: ^3.0.0

  # 📩 Firebase Messaging - For push notifications
  firebase_messaging: ^15.0.0

  # 🔔 Local notifications - For foreground notification handling
  flutter_local_notifications: ^17.1.2

  # Optional: State management
  provider: ^6.1.2

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/isupply.png