// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF6Uz56yH42hxGr2_Elu4oNSJti_2lGBw',
    appId: '1:698864423473:web:3b6727c5ce391f02237b10',
    messagingSenderId: '698864423473',
    projectId: 'isuuply-task',
    authDomain: 'isuuply-task.firebaseapp.com',
    storageBucket: 'isuuply-task.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBazRWSh953sxjG1KabQWJxhU4SnX4sr4g',
    appId: '1:698864423473:android:b558cac535496638237b10',
    messagingSenderId: '698864423473',
    projectId: 'isuuply-task',
    storageBucket: 'isuuply-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR9eJoWha2n9k5NyPU8EpEq81zi26VicQ',
    appId: '1:698864423473:ios:a4451a4c673c11af237b10',
    messagingSenderId: '698864423473',
    projectId: 'isuuply-task',
    storageBucket: 'isuuply-task.firebasestorage.app',
    iosBundleId: 'com.example.isupplytask1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR9eJoWha2n9k5NyPU8EpEq81zi26VicQ',
    appId: '1:698864423473:ios:a4451a4c673c11af237b10',
    messagingSenderId: '698864423473',
    projectId: 'isuuply-task',
    storageBucket: 'isuuply-task.firebasestorage.app',
    iosBundleId: 'com.example.isupplytask1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF6Uz56yH42hxGr2_Elu4oNSJti_2lGBw',
    appId: '1:698864423473:web:5bf8732a9a69b2c5237b10',
    messagingSenderId: '698864423473',
    projectId: 'isuuply-task',
    authDomain: 'isuuply-task.firebaseapp.com',
    storageBucket: 'isuuply-task.firebasestorage.app',
  );

}